name: Run Proxy Scanner

on: [workflow_dispatch]  # Cho phép bạn bấm "Run workflow" để chạy

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Scanner
      run: go build -o scanner main.go

    - name: Run Proxy Scanner
      run: ./scanner
